const data = {
    products: [
        {
            _id: '1',
            name: 'Vestido Cinderela',
            category: 'Vestidos',
            image: '/images/p1.jpg',
            price: 279,
            countInStock: 10,
            brand: 'EK',
            rating: 4.5,
            numReviews: 10,
            description: 'Vestido de alta qualidade da princesa do sapatinho de cristal',
        },
        {
            _id: '2',
            name: 'Vestido Jasmine',
            category: 'Vestidos',
            image: '/images/p2.jpg',
            price: 179,
            countInStock: 20,
            brand: 'EK',
            rating: 3.2,
            numReviews: 25,
            description: 'Vestido de alta qualidade',
        },
        {
            _id: '3',
            name: 'Vestido Cinderela',
            category: 'Vestidos',
            image: '/images/p1.jpg',
            price: 279,
            countInStock: 0,
            brand: 'EK',
            rating: 2.5,
            numReviews: 8,
            description: 'Vestido de alta qualidade da princesa do sapatinho de cristal',
        },
        {
            _id: '4',
            name: 'Vestido Jasmine',
            category: 'Vestidos',
            image: '/images/p2.jpg',
            price: 179,
            countInStock: 12,
            brand: 'EK',
            rating: 5,
            numReviews: 5,
            description: 'Vestido de alta qualidade',
        },
        {
            _id: '5',
            name: 'Vestido Cinderela',
            category: 'Vestidos',
            image: '/images/p1.jpg',
            price: 279,
            countInStock: 0,
            brand: 'EK',
            rating: 4.5,
            numReviews: 10,
            description: 'Vestido de alta qualidade da princesa do sapatinho de cristal',
        },
        {
            _id: '6',
            name: 'Vestido Jasmine',
            category: 'Vestidos',
            image: '/images/p2.jpg',
            price: 179,
            brand: 'EK',
            rating: 3.5,
            numReviews: 7,
            description: 'Vestido de alta qualidade',
        },
    ],
};
export default data